'''
Client Class

This class is for storing client data and maybe linking documents
to them. Internally it basically is just a Document, yet with some
kind of hard-coded DocumentType inside it. The idea is to have one
kind of 'document', which can be linked to other documents: clients
have invoices or quotes, for example. Maybe at some point (if not
already there) it will be possible to link documents between each
other. Yet I wanted to have some more restrict logic here: clients
and all their linked documents, which belong to them.
'''


from plainvoice.model.config import Config
from plainvoice.model.document.document import Document
from plainvoice.model.document.document import DocumentType


class Client(Document):
    '''
    This class holds information about the client.
    '''

    DEFAULT_FIELDS: dict = {
        'company': ('str', ''),
        'attention': ('str', 'Attn.'),
        'salutation': ('str', 'Mr.'),
        'first_name': ('str', ''),
        'last_name': ('str', ''),
        'street': ('str', ''),
        'post_code': ('str', ''),
        'country': ('str', ''),
        'city': ('str', ''),
        'language': ('str', '')
    }
    '''
    The dict describing the prebuilt fields and also
    holding the default values for it. It can describe
    the type of the prebuilt field and also fill its
    default value. I wanted to have this in one global
    variable so that it can get modified in one place
    easier.
    The key is the fieldname and its value is a tupple
    describing its type and default value.
    '''

    DEFAULT_FIELDS_TYPES: dict = {}
    DEFAULT_FIELDS_DEFAULTS: dict = {}
    '''
    These two variables are cache variables for the
    DEFAULT_FIELDS variable and will get filled
    on demand.
    '''

    def __init__(self, client_id: str = ''):
        '''
        This class is for clients data. It is supposed to be able
        to link to certain documents for the clients.

        Args:
            client_id (str): \
                The client id. (default: defined by the \
                method for finding the next id [TODO!].)
        '''
        super().__init__(client_id)

        self.init_document_type()

        # now the repository is set, now I can try to get
        # an automatic set next client_id / name for
        # this instance
        if client_id == '':
            client_id = self.get_next_code()

        # name and id of the object is the same
        # for client objects
        self.code = client_id
        self.name = client_id
        self.load_from_name(self.name)

    def fill_empty_prebuilt_fields(self) -> None:
        '''
        Fill the empty prebuilt fields, which will first
        be generated by the Document.fill_empty_prebuilt_fields()
        method and then fill those values with pre-filled
        data / defaults.
        '''
        self.data_prebuilt = self.generate_default_fields_dict('defaults')

    def from_dict(self, values: dict) -> None:
        '''
        Fill the objects attributes / data from the given dict.
        This overwrites the Document from_dict() method, which
        also have the from_dict_document_type() method in use.
        Yet for the client I need the hard coded DocumentType
        and thus does not want it be searched in the document
        types folder, since it should not exist there.

        Args:
            values (dict): The dict values to fill the object.
        '''
        self._from_dict_base(values)
        self._from_dict_data(values)

    def generate_default_fields_dict(self, what: str = '') -> dict:
        '''
        Getting or generating the default fields dict. It can
        be the fieldnames with its types, the fieldnames with
        its defautl values or even the plain DEFAULT_FIELDS
        constant of this class (as a fallback).

        Args:
            what (str): \
                Choose from `'types'`, `'defaults'` or aynthing \
                else to get the DEFAULT_FIELDS constant.

        Returns:
            dict: Returns the wanted dict.
        '''
        # initialize cache variables so that the for loop
        # will only have to run once.
        if (
            not self.DEFAULT_FIELDS_TYPES
            or not self.DEFAULT_FIELDS_DEFAULTS
        ):
            self.DEFAULT_FIELDS_TYPES = {}
            self.DEFAULT_FIELDS_DEFAULTS = {}
            for fieldname in self.DEFAULT_FIELDS:
                types = self.DEFAULT_FIELDS[fieldname][0]
                defaults = self.DEFAULT_FIELDS[fieldname][1]
                self.DEFAULT_FIELDS_TYPES[fieldname] = types
                self.DEFAULT_FIELDS_DEFAULTS[fieldname] = defaults
        if what == 'types':
            return self.DEFAULT_FIELDS_TYPES
        elif what == 'defaults':
            return self.DEFAULT_FIELDS_DEFAULTS
        else:
            return self.DEFAULT_FIELDS

    def init_document_type(self) -> None:
        '''
        Initialize the document type. The class gets
        inherited from the Document class and with this
        method I want to define a hard coded DocumentType
        for just this client class.
        '''
        # since this DocumentType is some how hard-coded,
        # I cannot define the name on init, since the
        # DocumentType init method would try to automatically
        # load the DocumentType. in that process it would
        # set the default folder to './' and somehow overwrite
        # my set folder here
        # TODO: Not sure, if this is a sign of quite bad
        #       coding practice, oh boy ...
        doc_type = DocumentType(
            '',
            Config().client_folder,
            Config().client_filename_pattern
        )
        doc_type.name = '_client'
        doc_type.set(
            'prebuilt_fields',
            self.generate_default_fields_dict('types')
        )
        self.document_type = doc_type

        # also set the folder for the repository. this method
        # otherwise would be executed in the set_document_type()
        # method of the Document class, yet this method also
        # loads the DocumentType by name. And here in this
        # Client class I need the hard coded document type.
        self.repository.set_folder(
            self.document_type.get('document_folder')
        )
        # same for filename_pattern
        self.repository.set_filename_pattern(
            self.document_type.get('document_filename_pattern')
        )

    def __str__(self) -> str:
        '''
        Represent this class as a string.

        Returns:
            srt: The readable string.
        '''
        client_id = self.code
        first = self.data_prebuilt['first_name']
        last = self.data_prebuilt['last_name']
        return f'{client_id}: {first} {last}'
